title: Austin Stanbury
url: "https://austinstanbury.com"
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:slug/
  artworks:
    output: true
    permalink: /art/:slug/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "artworks"
    values:
      layout: "artwork"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
